import './globals.css'
import { Inter as FontSans } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import Link from 'next/link'
import { cn } from '@/lib/utils'
import PokemonProvider from '@/store/PokemonProvider'
import { getPokemonList } from '@/lib/pokemonAPI'
import { Pokemon } from '@/type'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: `${process.env.BASE_PATH}/manifest.json`,
  keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
  generator: "Next.js",
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: `${process.env.BASE_PATH}/icon-192x192.png` },
    { rel: "icon", url: `${process.env.BASE_PATH}/icon-192x192.png` },
  ],
}

// Providers wrap around our application and give them access to data.
// NextThemesProvider - Give our application access to light / dark mode data.
// Providers are generally on the client side ("use client")
// Switch from light mode to dark mode <-- user interaction / needs the client to exist.

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const poke : Pokemon = await getPokemonList();
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={cn("bg-background font-sans antialiased scroll-smooth",fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <PokemonProvider poke={poke}>
            <main className="flex flex-col items-center p-5 lg:p-24 pb-0 lg:pb-0">
              <div className="z-10 items-center justify-between w-full max-w-5xl text-sm lg:flex">
                <Link href="/"><h2 className="text-2xl text-bold">PokemonFinder</h2></Link>
              </div>
              {children}
            </main>
          </PokemonProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
